{
 "title": "BW From API",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "import \"influxdata/influxdb/v1\"\nv1.measurements(bucket: v.bucket)"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${server}\"  )\n  |> filter(fn: (r) => r.measurement_type == \"traffic:download\" or r.measurement_type == \"traffic:upload\" )\n"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${server}\"  )\n  |> filter(fn: (r) => r.measurement_type == \"errors:download\" or r.measurement_type == \"errors:upload\" )\n"
    }
   ]
  },
  {
   "title": "Packets per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${server}\"  )\n  |> filter(fn: (r) => r.measurement_type == \"packets:download\" or r.measurement_type == \"packets:upload\" )\n"
    }
   ]
  }
 ]
}